name: Fetch Customer Reviews
# cron job
on:
  schedule:
    - cron: "0 * * * *"   # runs every hour
  workflow_dispatch:

jobs:
  fetch-reviews:
    runs-on: ubuntu-latest

    steps:
      - name: Trigger API cron job
        run: |
          curl -X POST https://customer-feedback-api.onrender.com/cron/fetch-reviews \
          -H "secret: ${{ secrets.CRON_SECRET }}"
